# Generated by Django 6.0.3 on 2026-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_university_link_alter_specialty_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='university',
        ),
        migrations.AddField(
            model_name='specialty',
            name='university',
            field=models.ManyToManyField(to='map.university', verbose_name='Университеты'),
        ),
    ]
