# Generated by Django 6.0.3 on 2026-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profession_link_alter_profession_description'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='created_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='professions',
            field=models.ManyToManyField(to='catalog.profession', verbose_name='Профессии'),
        ),
    ]
