# Generated by Django 6.0.4 on 2026-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=3, verbose_name='Баллы'),
        ),
    ]
