# Generated by Django 6.0.3 on 2026-05-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profession_link_alter_profession_description'),
        ('quiz', '0003_alter_answer_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Вариант ответа')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название теста'),
        ),
        migrations.CreateModel(
            name='QuestionProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='catalog.profession', verbose_name='Профессия')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_links', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Связь вопроса с профессией',
                'verbose_name_plural': 'Связи вопросов с профессиями',
                'unique_together': {('question', 'profession')},
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='professions',
        ),

        migrations.AddField(
            model_name='question',
            name='professions',
            field=models.ManyToManyField(
                related_name='questions',
                through='quiz.QuestionProfession',
                to='catalog.profession',
                verbose_name='Профессии'
            ),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
