# Generated by Django 6.0.3 on 2026-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anons',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
